### ISSUE TITLE
大佬，burp好像无法安装导入该插件

### ISSUE THREAD

**Issue by Ma1Dong** [woodpecker-appstore/weblogic-infodetector#1]
![图片](https://user-images.githubusercontent.com/52943794/127089249-5d65481d-4d59-459d-95b0-1a8ae35d16cd.png)

**Comment by c0ny1** [comment]
这个不是burp插件，是[woodpecker框架](https://github.com/woodpecker-framework/woodpecker-framwork-release)插件

**Comment by Ma1Dong** [comment]
好的大佬，呜呜呜
